### ISSUE TITLE
Document how to install using other plugin managers

### ISSUE THREAD

**Issue by mhalano** [svenXY/timewarrior#4]
I use the plugin manager `zgen` instead of use `oh-my-zsh` directly. Could be documentation about how to use the Timewarrior plugin with zgen and maybe other plugin managers.

**Comment by svenXY** [comment]
Hi,
the idea of zgen is to make it as easy as possible, therefore it would just boil down to
`zgen load svenXY/timewarrior` before running `zgen save` in your .zshrc

The generic approach for zgen is also described here: https://github.com/tarjoilija/zgen#general-zgen-functions

There are literally dozens of zsh plugin managers out there and all of them describe pretty well how to install a simple plugin from github, threrefore I don't see the point in repeating those instructions in my readme.

Cheers,
Sven
